- name: Set Apache package name (Ubuntu)
  set_fact:
    apache_package: apache2
  when: ansible_os_family == "Debian"

- name: Set Apache package name (CentOS)
  set_fact:
    apache_package: httpd
  when: ansible_os_family == "RedHat"

- name: Install Apache
  package:
    name: "{{ apache_package }}"
    state: present

- name: Start and enable Apache
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: true
