apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql-node1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /mnt/data/mysql1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube
  persistentVolumeReclaimPolicy: Retain
