apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.mysqlRootPassword }}
  MYSQL_DATABASE: {{ .Values.secrets.mysqlDatabase }}
  MYSQL_USER: {{ .Values.secrets.mysqlUser }}
  MYSQL_PASSWORD: {{ .Values.secrets.mysqlPassword }}
